name: Despliegue con Secreto

on:
  push:
    branches:
      - main

jobs:
  despliegue-con-secreto:
    runs-on: ubuntu-latest
    
    env:
      PINPON_SECRET: ${{ secrets.PINPON_SECRET }}
      PINPON_ENV: ${{ secrets.pinpon_env }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Modificar página web
        run: |
          # Agregar el secreto al archivo JavaScript
          echo "const secretValue = '$PINPON_SECRET';" > script.js

      - name: Desplegar HTML en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./
          publish_branch: gh-pages




